### ISSUE TITLE
no styling ?

### ISSUE THREAD

**Issue by zieru** [thephpleague/html-to-markdown#163] opened 2018-09-23 08:34 UTC
html:
`<p><img style="width: 353.101px; height: 264px;" src="http://172.28.136.242/myportal/uploads/38b904231774827cd13aae4b18ffb493_1537689581.jpg"></p><p><br></p><p>test</p>`

after markdown::
`![](http://172.28.136.242/myportal/uploads/38b904231774827cd13aae4b18ffb493_1537689581.jpg) test`

**Comment by colinodell** [comment] 2018-09-23 12:16
Yeah, this library does not preserve your styles because Markdown does not have a way to represent those.  (Technically we _could_ keep that `<img>` tag as HTML, which would work, but I'd want that to be an opt-in feature like #163)

Because this is technically the expected behavior I am going to close this, but please feel free to continue the discussion here or in #164!

**Closed by colinodell** 2018-09-23 12:16 UTC
Labels: question
