### ISSUE TITLE
Closing EM tag with a space immediately before it generates incorrect CommonMark (I think)

### ISSUE THREAD

**Issue by patternseek** [thephpleague/html-to-markdown#93] opened 2016-02-16 14:06 UTC
```php
    public function testConversion(){
        $converter = new HtmlConverter();
        $markdown = $converter->convert( "<em>Something </em>" );
        $converter = new CommonMarkConverter();
        $html = $converter->convertToHtml( $markdown );
        $this->assertEquals( "<p><em>Something</em></p>", $html );
    }
```

The initial HTML is converted to "_Something _" in markdown, note the space before the final underscore. This seems to break this part of the CommonMark spec: 

> A single _ character can close emphasis iff it is part of a right-flanking delimiter run and either (a) not part of a left-flanking delimiter run or (b) part of a left-flanking delimiter run followed by punctuation.

It means that when converted back to HTML with CommonMarkConvertor you get: 
```html
<p>_Something _</p>
```

**Comment by colinodell** [comment] 2016-02-16 19:03
We may need to trim the inner contents of the `<em>` to fix this issue.

**Comment by patternseek** [comment] 2016-02-16 21:18
I think it happens with BR too which I imagine would complicate things but I've not had time to test I'm afraid, a bit hectic at the moment.

**Comment by andreskrey** [comment] 2016-10-08 11:10
Could not reproduce on 4.2.2

Input:

`<em>Something </em>`

Actual:

`_Something_ `

Expected:

`_Something_ `

Notice that there's an extra space after the closing _
If this is an issue I can create a quick pr to solve this.

**Comment by colinodell** [comment] 2016-10-10 16:13
Closed - no longer an issue

**Closed by colinodell** 2016-10-10 16:13 UTC
Labels: bug, commonmark-compatibility, low-hanging-fruit, up-for-grabs
