### ISSUE TITLE
 when i deal it with chinese , i always got a strange charater like �

### ISSUE THREAD

**Issue by JellyBool** [thephpleague/html-to-markdown#54] opened 2015-09-18 14:35 UTC
i parser the html with php-simple-html-dom,but when i try to convert it to markdown,i always got �,

what can i do

**Comment by colinodell** [comment] 2015-09-18 16:59
Could you provide an example of HTML which causes this issue?

**Comment by JellyBool** [comment] 2015-09-20 14:20
thx for reply，

html,i use something like php-simple-dom-parser to select `<div class="article fmt">` tag

```
<div class="article fmt">
                    
<h2 id="articleHeader0">前言</h2>
<p>第三方登录认证能简化用户登录/注册的操作，降低用户登录/注册的门槛，对提高应用的用户转化率很有帮助。</p>
<h2 id="articleHeader1">Socialite</h2>
<p>Laravel 为我们提供了简单、易用的方式，使用 <a href="https://github.com/laravel/socialite" target="_blank">Laravel Socialite</a> 进行 OAuth（OAuth1 和 OAuth2 都有支持） 认证。</p>
<p>Socialite 目前支持的认证有 Facebook、Twitter、Google、LinkedIn、GitHub、Bitbucket。（恩，有一半是“不存在”的网站。）<br>Socialite 的用法官方文档中已经讲得很详细了，恕不赘述。<br>英文好的同学，建议直接看 Laravel 官方文档，<a href="http://www.jianshu.com/p/2b7e4635f1e6" target="_blank">毕竟看二手知识是有高风险的</a>。<br>英文不好的同学（比如我），下面是中文文档：<br>Laravel 5.0：<a href="http://laravel-china.org/docs/5.0/authentication#social-authentication" target="_blank">http://laravel-china.org/docs/5.0/authentication#social-authentication</a><br>Laravel 5.1：<a href="http://laravel.tw/docs/5.1/authentication#social-authentication" target="_blank">http://laravel.tw/docs/5.1/authentication#social-authentication</a></p>
<h2 id="articleHeader2">SocialiteProviders</h2>
<p><a href="https://github.com/SocialiteProviders" target="_blank">SocialiteProviders</a>  通过扩展 Socialite 的 Driver，实现了很多第三方认证。国内的有：微博、QQ、微信、豆瓣。当然你自己也可以参照实现其他的，只要那个网站支持 OAuth。<br>SocialiteProviders 的使用也超级简单易用，每个都对应了文档。其实，不懂英文也能看懂。<br>文档地址：<a href="http://socialiteproviders.github.io/" target="_blank">http://socialiteproviders.github.io/</a><br><strong>其实，文章到这里就应该结束了</strong>。由于文档是基于 Laravel5.0 的，所以我还是打算基于 Laravel5.1 演示一遍，并说一下要注意的地方吧。</p>
<h2 id="articleHeader3">以 Weibo 为例</h2>
<h3 id="articleHeader4">1.安装</h3>
<div class="widget-codetool" style="display:none;"><a href="javascript:void(0);" class="selectCode">全选</a><a href="javascript:void(0);" class="copyCode" data-clipboard-text="composer require socialiteproviders/weibo" data-toggle="tooltip" data-placement="top" title="">复制</a><a href="javascript:void(0);" class="saveToNote">放进笔记</a></div><pre class="hljs coffeescript"><code class="shell">composer <span class="hljs-built_in">require</span> socialiteproviders/weibo</code></pre>
<h3 id="articleHeader5">2.添加 Service Provider</h3>
<p>如果之前添加过 Socialite Provider，得先注释掉：<br>文件 <code>config/app.php</code></p>
<div class="widget-codetool" style="display:none;"><a href="javascript:void(0);" class="selectCode">全选</a><a href="javascript:void(0);" class="copyCode" data-clipboard-text="'providers' => [
//    Laravel\Socialite\SocialiteServiceProvider::class,
    SocialiteProviders\Manager\ServiceProvider::class, // add
]," data-toggle="tooltip" data-placement="top" title="">复制</a><a href="javascript:void(0);" class="saveToNote">放进笔记</a></div><pre><code class="php"><span class="hljs-string">'providers'</span> =&gt; [
<span class="hljs-comment">//    Laravel\Socialite\SocialiteServiceProvider::class,</span>
    SocialiteProviders\Manager\ServiceProvider::<span class="hljs-class"><span class="hljs-keyword">class</span>, // <span class="hljs-title">add</span>
],</span></code></pre>
<h3 id="articleHeader6">3.添加 Facades Aliase</h3>
<p>如果之前安装 Socialite 时添加过，就不需要再添加了。<br>还是文件 <code>config/app.php</code></p>
<div class="widget-codetool" style="display:none;"><a href="javascript:void(0);" class="selectCode">全选</a><a href="javascript:void(0);" class="copyCode" data-clipboard-text="'aliases' => [
    'Socialite' => Laravel\Socialite\Facades\Socialite::class, // add
],
" data-toggle="tooltip" data-placement="top" title="">复制</a><a href="javascript:void(0);" class="saveToNote">放进笔记</a></div><pre><code class="php"><span class="hljs-string">'aliases'</span> =&gt; [
    <span class="hljs-string">'Socialite'</span> =&gt; Laravel\Socialite\Facades\Socialite::<span class="hljs-class"><span class="hljs-keyword">class</span>, // <span class="hljs-title">add</span>
],
</span></code></pre>
<h3 id="articleHeader7">4.添加事件处理器</h3>
<p>文件 <code>app/Providers/EventServiceProvider.php</code></p>
<div class="widget-codetool" style="display:none;"><a href="javascript:void(0);" class="selectCode">全选</a><a href="javascript:void(0);" class="copyCode" data-clipboard-text="protected $listen = [
    'SocialiteProviders\Manager\SocialiteWasCalled' => [
        'SocialiteProviders\Weibo\WeiboExtendSocialite@handle',
    ],
];" data-toggle="tooltip" data-placement="top" title="">复制</a><a href="javascript:void(0);" class="saveToNote">放进笔记</a></div><pre><code class="php"><span class="hljs-keyword">protected</span> <span class="hljs-variable">$listen</span> = [
    <span class="hljs-string">'SocialiteProviders\Manager\SocialiteWasCalled'</span> =&gt; [
        <span class="hljs-string">'SocialiteProviders\Weibo\WeiboExtendSocialite@handle'</span>,
    ],
];</code></pre>
<p>这里顺便提一下 SocialiteProviders 的原理。</p>
<p><code>SocialiteProviders\Manager\ServiceProvider</code> 实际上是继承于 <code>Laravel\Socialite\SocialiteServiceProvider</code> 的，这是它的源码：</p>
<div class="widget-codetool" style="display:none;"><a href="javascript:void(0);" class="selectCode">全选</a><a href="javascript:void(0);" class="copyCode" data-clipboard-text="<?php

namespace SocialiteProviders\Manager;

use Illuminate\Contracts\Events\Dispatcher;
use Laravel\Socialite\SocialiteServiceProvider;

class ServiceProvider extends SocialiteServiceProvider
{
    /**
     * @param Dispatcher         $event
     * @param SocialiteWasCalled $socialiteWasCalled
     */
    public function boot(Dispatcher $event, SocialiteWasCalled $socialiteWasCalled)
    {
        $event->fire($socialiteWasCalled);
    }
}
" data-toggle="tooltip" data-placement="top" title="">复制</a><a href="javascript:void(0);" class="saveToNote">放进笔记</a></div><pre><code class="php"><span class="hljs-preprocessor">&lt;?php</span>

<span class="hljs-keyword">namespace</span> <span class="hljs-title">SocialiteProviders</span>\<span class="hljs-title">Manager</span>;

<span class="hljs-keyword">use</span> <span class="hljs-title">Illuminate</span>\<span class="hljs-title">Contracts</span>\<span class="hljs-title">Events</span>\<span class="hljs-title">Dispatcher</span>;
<span class="hljs-keyword">use</span> <span class="hljs-title">Laravel</span>\<span class="hljs-title">Socialite</span>\<span class="hljs-title">SocialiteServiceProvider</span>;

<span class="hljs-class"><span class="hljs-keyword">class</span> <span class="hljs-title">ServiceProvider</span> <span class="hljs-keyword">extends</span> <span class="hljs-title">SocialiteServiceProvider</span>
</span>{
    <span class="hljs-comment">/**
     *<span class="hljs-phpdoc"> @param</span> Dispatcher         $event
     *<span class="hljs-phpdoc"> @param</span> SocialiteWasCalled $socialiteWasCalled
     */</span>
    <span class="hljs-keyword">public</span> <span class="hljs-function"><span class="hljs-keyword">function</span> <span class="hljs-title">boot</span><span class="hljs-params">(Dispatcher <span class="hljs-variable">$event</span>, SocialiteWasCalled <span class="hljs-variable">$socialiteWasCalled</span>)</span>
    </span>{
        <span class="hljs-variable">$event</span>-&gt;fire(<span class="hljs-variable">$socialiteWasCalled</span>);
    }
}
</code></pre>
<p>它只是在启动时会触发 <code>SocialiteWasCalled</code> 事件，刚才在 <code>SocialiteProviders\Manager\SocialiteWasCalled</code> 事件的监听器中加上了事件处理器：<code>SocialiteProviders\Weibo\WeiboExtendSocialite@handle</code>。处理器的源码：</p>
<div class="widget-codetool" style="display:none;"><a href="javascript:void(0);" class="selectCode">全选</a><a href="javascript:void(0);" class="copyCode" data-clipboard-text="<?php

namespace SocialiteProviders\Weibo;

use SocialiteProviders\Manager\SocialiteWasCalled;

class WeiboExtendSocialite
{
    public function handle(SocialiteWasCalled $socialiteWasCalled)
    {
        $socialiteWasCalled->extendSocialite('weibo', __NAMESPACE__.'\Provider');
    }
}
" data-toggle="tooltip" data-placement="top" title="">复制</a><a href="javascript:void(0);" class="saveToNote">放进笔记</a></div><pre><code class="php"><span class="hljs-preprocessor">&lt;?php</span>

<span class="hljs-keyword">namespace</span> <span class="hljs-title">SocialiteProviders</span>\<span class="hljs-title">Weibo</span>;

<span class="hljs-keyword">use</span> <span class="hljs-title">SocialiteProviders</span>\<span class="hljs-title">Manager</span>\<span class="hljs-title">SocialiteWasCalled</span>;

<span class="hljs-class"><span class="hljs-keyword">class</span> <span class="hljs-title">WeiboExtendSocialite</span>
</span>{
    <span class="hljs-keyword">public</span> <span class="hljs-function"><span class="hljs-keyword">function</span> <span class="hljs-title">handle</span><span class="hljs-params">(SocialiteWasCalled <span class="hljs-variable">$socialiteWasCalled</span>)</span>
    </span>{
        <span class="hljs-variable">$socialiteWasCalled</span>-&gt;extendSocialite(<span class="hljs-string">'weibo'</span>, <span class="hljs-keyword">__NAMESPACE__</span>.<span class="hljs-string">'\Provider'</span>);
    }
}
</code></pre>
<p>处理器做的事情就是为 Socialite 添加了一个 weibo Driver，这样就可以使用 weibo 的 Driver 了。</p>
<h3 id="articleHeader8">5.添加路由</h3>
<p>文件 <code>app/Http/routes.php</code></p>
<div class="widget-codetool" style="display:none;"><a href="javascript:void(0);" class="selectCode">全选</a><a href="javascript:void(0);" class="copyCode" data-clipboard-text="// 引导用户到新浪微博的登录授权页面
Route::get('auth/weibo', 'Auth\AuthController@weibo');
// 用户授权后新浪微博回调的页面
Route::get('auth/callback', 'Auth\AuthController@callback');" data-toggle="tooltip" data-placement="top" title="">复制</a><a href="javascript:void(0);" class="saveToNote">放进笔记</a></div><pre><code class="php"><span class="hljs-comment">// 引导用户到新浪微博的登录授权页面</span>
Route::get(<span class="hljs-string">'auth/weibo'</span>, <span class="hljs-string">'Auth\AuthController@weibo'</span>);
<span class="hljs-comment">// 用户授权后新浪微博回调的页面</span>
Route::get(<span class="hljs-string">'auth/callback'</span>, <span class="hljs-string">'Auth\AuthController@callback'</span>);</code></pre>
<h3 id="articleHeader9">6.配置</h3>
<p>文件 <code>config/services.php</code></p>
<div class="widget-codetool" style="display:none;"><a href="javascript:void(0);" class="selectCode">全选</a><a href="javascript:void(0);" class="copyCode" data-clipboard-text="'weibo' => [
    'client_id' => env('WEIBO_KEY'),
    'client_secret' => env('WEIBO_SECRET'),
    'redirect' => env('WEIBO_REDIRECT_URI'),  
]," data-toggle="tooltip" data-placement="top" title="">复制</a><a href="javascript:void(0);" class="saveToNote">放进笔记</a></div><pre><code class="php"><span class="hljs-string">'weibo'</span> =&gt; [
    <span class="hljs-string">'client_id'</span> =&gt; env(<span class="hljs-string">'WEIBO_KEY'</span>),
    <span class="hljs-string">'client_secret'</span> =&gt; env(<span class="hljs-string">'WEIBO_SECRET'</span>),
    <span class="hljs-string">'redirect'</span> =&gt; env(<span class="hljs-string">'WEIBO_REDIRECT_URI'</span>),  
],</code></pre>
<p>文件 <code>.env</code></p>
<div class="widget-codetool" style="display:none;"><a href="javascript:void(0);" class="selectCode">全选</a><a href="javascript:void(0);" class="copyCode" data-clipboard-text="WEIBO_KEY=yourkeyfortheservice
WEIBO_SECRET=yoursecretfortheservice
WEIBO_REDIRECT_URI=http://192.168.1.7/laravel/public/auth/callback" data-toggle="tooltip" data-placement="top" title="">复制</a><a href="javascript:void(0);" class="saveToNote">放进笔记</a></div><pre><code class="php">WEIBO_KEY=yourkeyfortheservice
WEIBO_SECRET=yoursecretfortheservice
WEIBO_REDIRECT_URI=http:<span class="hljs-comment">//192.168.1.7/laravel/public/auth/callback</span></code></pre>
<p><strong>注意：192.168.1.7 是我本地虚拟机的地址，虚拟机可以连外网就可以测试了。貌似 QQ 的必须绑定域名才是测试。</strong></p>
<p>当然，直接将配置的具体参数写在 <code>config/services.php</code> 中也是可以的，但是不推荐这样。因为 <code>config/services.php</code> 属于代码文件，而 <code>.env</code> 属于配置文件。当代码上线是只要应用线上环境的配置文件即可，而不需要改动代码文件，这算是一个最佳实践吧。<br>至于 <code>WEIBO_KEY</code> 和 <code>WEIBO_SECRET</code> 的具体值，这个是由新浪微博分发给你的，在新浪微博的<strong>授权回调页</strong>中填写 <code>WEIBO_REDIRECT_URI</code>。这些细节已经超出本文的内容，建议直接到 <a href="http://open.weibo.com" target="_blank">http://open.weibo.com</a> 查阅新浪微博的手册。</p>
<h3 id="articleHeader10">7.代码实现</h3>
<p>文件 <code>app/Http/Controllers/Auth/AuthController.php</code></p>
<div class="widget-codetool" style="display:none;"><a href="javascript:void(0);" class="selectCode">全选</a><a href="javascript:void(0);" class="copyCode" data-clipboard-text="    public function weibo() {
        return \Socialite::with('weibo')->redirect();
        // return \Socialite::with('weibo')->scopes(array('email'))->redirect();
    }


    public function callback() {
        $oauthUser = \Socialite::with('weibo')->user();

        var_dump($oauthUser->getId());
        var_dump($oauthUser->getNickname());
        var_dump($oauthUser->getName());
        var_dump($oauthUser->getEmail());
        var_dump($oauthUser->getAvatar());
    }" data-toggle="tooltip" data-placement="top" title="">复制</a><a href="javascript:void(0);" class="saveToNote">放进笔记</a></div><pre><code class="php">    <span class="hljs-keyword">public</span> <span class="hljs-function"><span class="hljs-keyword">function</span> <span class="hljs-title">weibo</span><span class="hljs-params">()</span> </span>{
        <span class="hljs-keyword">return</span> \Socialite::with(<span class="hljs-string">'weibo'</span>)-&gt;redirect();
        <span class="hljs-comment">// return \Socialite::with('weibo')-&gt;scopes(array('email'))-&gt;redirect();</span>
    }


    <span class="hljs-keyword">public</span> <span class="hljs-function"><span class="hljs-keyword">function</span> <span class="hljs-title">callback</span><span class="hljs-params">()</span> </span>{
        <span class="hljs-variable">$oauthUser</span> = \Socialite::with(<span class="hljs-string">'weibo'</span>)-&gt;user();

        var_dump(<span class="hljs-variable">$oauthUser</span>-&gt;getId());
        var_dump(<span class="hljs-variable">$oauthUser</span>-&gt;getNickname());
        var_dump(<span class="hljs-variable">$oauthUser</span>-&gt;getName());
        var_dump(<span class="hljs-variable">$oauthUser</span>-&gt;getEmail());
        var_dump(<span class="hljs-variable">$oauthUser</span>-&gt;getAvatar());
    }</code></pre>
<p>访问 <code>http://192.168.1.7/laravel/public/auth/weibo</code>，会跳转到新浪微博的登录授权页面，授权成功后，会跳转到 <code>http://192.168.1.7/laravel/public/auth/callback</code><br>返回的结果：</p>
<div class="widget-codetool" style="display:none;"><a href="javascript:void(0);" class="selectCode">全选</a><a href="javascript:void(0);" class="copyCode" data-clipboard-text="string(10) &quot;3221174302&quot;
string(11) &quot;Mr_Jing1992&quot;
NULL
NULL
string(50) &quot;http://tp3.sinaimg.cn/3221174302/180/40064692810/1&quot;" data-toggle="tooltip" data-placement="top" title="">复制</a><a href="javascript:void(0);" class="saveToNote">放进笔记</a></div><pre><code class="php">string(<span class="hljs-number">10</span>) <span class="hljs-string">"3221174302"</span>
string(<span class="hljs-number">11</span>) <span class="hljs-string">"Mr_Jing1992"</span>
<span class="hljs-keyword">NULL</span>
<span class="hljs-keyword">NULL</span>
string(<span class="hljs-number">50</span>) <span class="hljs-string">"http://tp3.sinaimg.cn/3221174302/180/40064692810/1"</span></code></pre>
<p>user 对象是现实了接口 <code>Laravel\Socialite\Contracts\User</code> 的，有以下几个方法：</p>
<div class="widget-codetool" style="display:none;"><a href="javascript:void(0);" class="selectCode">全选</a><a href="javascript:void(0);" class="copyCode" data-clipboard-text="<?php

namespace Laravel\Socialite\Contracts;

interface User
{
    public function getId();
    public function getNickname();
    public function getName();
    public function getEmail();
    public function getAvatar();
}
" data-toggle="tooltip" data-placement="top" title="">复制</a><a href="javascript:void(0);" class="saveToNote">放进笔记</a></div><pre><code class="php"><span class="hljs-preprocessor">&lt;?php</span>

<span class="hljs-keyword">namespace</span> <span class="hljs-title">Laravel</span>\<span class="hljs-title">Socialite</span>\<span class="hljs-title">Contracts</span>;

<span class="hljs-class"><span class="hljs-keyword">interface</span> <span class="hljs-title">User</span>
</span>{
    <span class="hljs-keyword">public</span> <span class="hljs-function"><span class="hljs-keyword">function</span> <span class="hljs-title">getId</span><span class="hljs-params">()</span></span>;
    <span class="hljs-keyword">public</span> <span class="hljs-function"><span class="hljs-keyword">function</span> <span class="hljs-title">getNickname</span><span class="hljs-params">()</span></span>;
    <span class="hljs-keyword">public</span> <span class="hljs-function"><span class="hljs-keyword">function</span> <span class="hljs-title">getName</span><span class="hljs-params">()</span></span>;
    <span class="hljs-keyword">public</span> <span class="hljs-function"><span class="hljs-keyword">function</span> <span class="hljs-title">getEmail</span><span class="hljs-params">()</span></span>;
    <span class="hljs-keyword">public</span> <span class="hljs-function"><span class="hljs-keyword">function</span> <span class="hljs-title">getAvatar</span><span class="hljs-params">()</span></span>;
}
</code></pre>
<p>当然，并不是有了这些方法就一定能获取到你需要的数据的。比如，在新浪的接口中，想要获取用户的 email 是得用户授权的，得到授权后请求获取邮箱的接口，才能拿到用户的邮箱。<br>详情参见：<br><a href="http://open.weibo.com/wiki/Scope" target="_blank">http://open.weibo.com/wiki/Scope</a><br><a href="http://open.weibo.com/wiki/2/account/profile/email" target="_blank">http://open.weibo.com/wiki/2/account/profile/email</a></p>
<p>但是，id 这个应该是所有第三方认证服务提供商都会返回的。不然那就没有办法作账号关联了。</p>
<p>获取到第三方的 id 后，如果这个 id 和你网站用户账号有绑定，就直接登录你网站用户的账号。如果没有任何账号与之绑定，就应该提示用户绑定已有账号或者是注册新账号什么的，这些具体逻辑就不在多说了。还有，在新浪上面还有一个<strong>取消授权回调页</strong>的值需要填，是用户在授权页点击“取消”按钮时新浪回调的页面。这个可以设置为你网站的登录页面或者其他页面。</p>
<p>补充：<br><a href="http://socialiteproviders.github.io/providers/qq/" target="_blank">http://socialiteproviders.github.io/providers/qq/</a> 文档中有一处错误。<br><code>SocialiteProviders\QQ\QqExtendSocialite@handle</code> 应该改为：<code>SocialiteProviders\Qq\QqExtendSocialite@handle</code>。<strong>注意大小写</strong>。</p>
<p>最后：<br>如有错误，还望指正。</p>

                </div>

```

markdown output
```
## 前言

第三方登录认证能简化用户登录/注册的操作，降低用户登录/注册的门槛，对提高应用的用户转化率很有帮助。

## Socialite

Laravel 为我们提供了简单、易用的方式，使用 [Laravel Socialite][1] 进行 OAuth（OAuth1 和 OAuth2 都有支持） 认证。

Socialite 目前支持的认证有 Facebook、Twitter、Google、LinkedIn、GitHub、Bitbucket。（恩，有一半是“不存在”的网站。）  
Socialite 的用法官方文档中已经讲得很详细了，恕不赘述。  
英文好的同学，建议直接看 Laravel 官方文档，[毕竟看二手知识是有高风险的][2]。  
英文不好的同学（比如我），下面是中文文档：  
Laravel 5.0：<http://laravel-china.org/docs/5.0/authentication#social-authentication>  
Laravel 5.1：<http://laravel.tw/docs/5.1/authentication#social-authentication>

## SocialiteProviders

[SocialiteProviders][3] 通过扩展 Socialite 的 Driver，实现了很多第三方认证。国� 的有：微博、QQ、微信、豆瓣。当然� 自己也可以参� �实现� �他的，只要那个网站支持 OAuth。  
SocialiteProviders 的使用也� 级简单易用，每个都对应了文档。� �实，不懂英文也能看懂。  
文档地址：<http://socialiteproviders.github.io/>  
**� �实，文� 到这里就应该结束了**。由于文档是基于 Laravel5.0 的，所以我还是打算基于 Laravel5.1 演示一遍，并说一下要注意的地方吧。

## 以 Weibo 为例

### 1.安� 

<pre><code class="shell">composer require socialiteproviders/weibo</code></pre>

### 2.添� Service Provider

如果之前添� 过 Socialite Provider，得� �注释掉：  
文件 `config/app.php`

<pre><code class="php">'providers' => [ //    Laravel\Socialite\SocialiteServiceProvider::class,     SocialiteProviders\Manager\ServiceProvider::class, // add ],</code></pre>

### 3.添� Facades Aliase

如果之前安� Socialite 时添� 过，就不需要再添� 了。  
还是文件 `config/app.php`

<pre><code class="php">'aliases' => [     'Socialite' => Laravel\Socialite\Facades\Socialite::class, // add ], </code></pre>

### 4.添� 事件处理器

文件 `app/Providers/EventServiceProvider.php`

<pre><code class="php">protected $listen = [     'SocialiteProviders\Manager\SocialiteWasCalled' => [         'SocialiteProviders\Weibo\WeiboExtendSocialite@handle',     ], ];</code></pre>

这里顺便提一下 SocialiteProviders 的原理。

`SocialiteProviders\Manager\ServiceProvider` 实� 上是继承于 `Laravel\Socialite\SocialiteServiceProvider` 的，这是它的源� �：

<pre><code class="php"><?php  namespace SocialiteProviders\Manager;  use Illuminate\Contracts\Events\Dispatcher; use Laravel\Socialite\SocialiteServiceProvider;  class ServiceProvider extends SocialiteServiceProvider {     /**      * @param Dispatcher         $event      * @param SocialiteWasCalled $socialiteWasCalled      */     public function boot(Dispatcher $event, SocialiteWasCalled $socialiteWasCalled)     {         $event->fire($socialiteWasCalled);     } } </code></pre>

它只是在启动时会触发 `SocialiteWasCalled` 事件，刚才在 `SocialiteProviders\Manager\SocialiteWasCalled` 事件的监听器中� 上了事件处理器：`SocialiteProviders\Weibo\WeiboExtendSocialite@handle`。处理器的源� �：

<pre><code class="php"><?php  namespace SocialiteProviders\Weibo;  use SocialiteProviders\Manager\SocialiteWasCalled;  class WeiboExtendSocialite {     public function handle(SocialiteWasCalled $socialiteWasCalled)     {         $socialiteWasCalled->extendSocialite('weibo', __NAMESPACE__.'\Provider');     } } </code></pre>

处理器做的事� 就是为 Socialite 添� 了一个 weibo Driver，这� �就可以使用 weibo 的 Driver 了。

### 5.添� 路由

文件 `app/Http/routes.php`

<pre><code class="php">// 引导用户到新浪微博的登录授权页面 Route::get('auth/weibo', 'Auth\AuthController@weibo'); // 用户授权后新浪微博回调的页面 Route::get('auth/callback', 'Auth\AuthController@callback');</code></pre>

### 6.� �置

文件 `config/services.php`

<pre><code class="php">'weibo' => [     'client_id' => env('WEIBO_KEY'),     'client_secret' => env('WEIBO_SECRET'),     'redirect' => env('WEIBO_REDIRECT_URI'),   ],</code></pre>

文件 `.env`

<pre><code class="php">WEIBO_KEY=yourkeyfortheservice WEIBO_SECRET=yoursecretfortheservice WEIBO_REDIRECT_URI=http://192.168.1.7/laravel/public/auth/callback</code></pre>

**注意：192.168.1.7 是我本地虚拟机的地址，虚拟机可以连外网就可以测试了。貌似 QQ 的� 须绑定域名才是测试。**

当然，直接将� �置的� �体参数写在 `config/services.php` 中也是可以的，但是不推荐这� �。� 为 `config/services.php` 属于代� �文件，而 `.env` 属于� �置文件。当代� �上线是只要应用线上环境的� �置文件即可，而不需要改动代� �文件，这算是一个最佳实践吧。  
至于 `WEIBO_KEY` 和 `WEIBO_SECRET` 的� �体值，这个是由新浪微博分发给� 的，在新浪微博的**授权回调页**中填写 `WEIBO_REDIRECT_URI`。这些细节已经� 出本文的� 容，建议直接到 <http://open.weibo.com> 查� 新浪微博的手册。

### 7.代� �实现

文件 `app/Http/Controllers/Auth/AuthController.php`

<pre><code class="php">    public function weibo() {         return \Socialite::with('weibo')->redirect();         // return \Socialite::with('weibo')->scopes(array('email'))->redirect();     }       public function callback() {         $oauthUser = \Socialite::with('weibo')->user();          var_dump($oauthUser->getId());         var_dump($oauthUser->getNickname());         var_dump($oauthUser->getName());         var_dump($oauthUser->getEmail());         var_dump($oauthUser->getAvatar());     }</code></pre>

访问 `http://192.168.1.7/laravel/public/auth/weibo`，会跳转到新浪微博的登录授权页面，授权成功后，会跳转到 `http://192.168.1.7/laravel/public/auth/callback`  
返回的结果：

<pre><code class="php">string(10) "3221174302" string(11) "Mr_Jing1992" NULL NULL string(50) "http://tp3.sinaimg.cn/3221174302/180/40064692810/1"</code></pre>

user 对象是现实了接口 `Laravel\Socialite\Contracts\User` 的，有以下� 个方法：

<pre><code class="php"><?php  namespace Laravel\Socialite\Contracts;  interface User {     public function getId();     public function getNickname();     public function getName();     public function getEmail();     public function getAvatar(); } </code></pre>

当然，并不是有了这些方法就一定能获取到� 需要的数据的。比如，在新浪的接口中，想要获取用户的 email 是得用户授权的，得到授权后请求获取邮箱的接口，才能拿到用户的邮箱。  
详� 参见：  
<http://open.weibo.com/wiki/Scope>  
<http://open.weibo.com/wiki/2/account/profile/email>

但是，id 这个应该是所有第三方认证服务提供商都会返回的。不然那就没有办法作账号� �联了。

获取到第三方的 id 后，如果这个 id 和� 网站用户账号有绑定，就直接登录� 网站用户的账号。如果没有任何账号与之绑定，就应该提示用户绑定已有账号或� 是注册新账号什么的，这些� �体逻辑就不在多说了。还有，在新浪上面还有一个**取消授权回调页**的值需要填，是用户在授权页点击“取消”按钮时新浪回调的页面。这个可以设置为� 网站的登录页面或� � �他页面。

补� ：  
<http://socialiteproviders.github.io/providers/qq/> 文档中有一处错误。  
`SocialiteProviders\QQ\QqExtendSocialite@handle` 应该改为：`SocialiteProviders\Qq\QqExtendSocialite@handle`。**注意大小写**。

最后：  
如有错误，还望指正。

 [1]: https://github.com/laravel/socialite
 [2]: http://www.jianshu.com/p/2b7e4635f1e6
 [3]: https://github.com/SocialiteProviders
```

**Comment by colinodell** [comment] 2015-09-20 15:26
I'm unable to replicate this issue.  I get the following results with your HTML:

![image](https://cloud.githubusercontent.com/assets/202034/9981397/db77a582-5f89-11e5-8edb-4b7183af8e64.png)

(That script is a new feature I'm adding via #55, if you'd like to try it yourself.)

Is it possible that there's a character encoding issue somewhere else?  Some things to check:

- Are you viewing the Markdown in a UTF-8 compatible program?
- If you're viewing the Markdown in a browser, are you setting the charset properly?
- Is this being stored in a database which isn't configured for UTF-8?
- Have you confirmed that the php-simple-dom-parser output doesn't contain the � characters?
- Are you doing anything with the output of php-simple-dom-parser before sending it into this library?
- Are you doing anything with the output of this library before saving or displaying it?

**Comment by JellyBool** [comment] 2015-09-20 18:05
@colinodell 

thx，i will try the script。

answers  to the questions:

* yes
* yes
* not sure because i crawl from a website ,not store into database 
* yes , i almost debug every step
* no , i just select the <div> and put into the library(i check the html alone,it's perfect)
* i would say no cause i just use file_put_contents() function to save it as a md file

thx, any way

**Comment by colinodell** [comment] 2015-09-27 14:52
I still feel like this issue is being caused by feeding the HTML or Markdown through something which isn't UTF-8 aware.  I'm going to close this issue, as I'm unable to replicate it. But if you can definitively isolate the issue to within the library, and provide a standalone test case demonstrate the issue, I will gladly re-open this.

Thanks!

**Closed by colinodell** 2015-09-27 14:52 UTC
Labels: question
